services:
  - type: web
    name: matopedia
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: INVITE_CODE
        sync: false
      - key: ADMIN_TOKEN
        sync: false
